### ISSUE TITLE
Missing support for php 8.0?

### ISSUE THREAD

**Issue by ghost** [Rareloop/lumberjack-core#34]
What are the steps to reproduce this issue?
-------------------------------------------
1. Install php 8.0
2. Try composer update

![Screenshot 2021-11-14 at 20 29 18](https://user-images.githubusercontent.com/53090349/141695629-065c477f-cb3b-42e2-8c4d-8aa1175a3a75.png)

What happens?
-------------

![Screenshot 2021-11-14 at 20 29 06](https://user-images.githubusercontent.com/53090349/141695622-3fb0af48-3e05-44b7-bac9-991f6d9b670c.png)

**Comment by nocttuam** [comment]
I have a similar problem with PHP 8.0.13 

![image](https://user-images.githubusercontent.com/1095758/143502170-e584c723-06ae-401b-8e9e-852ed2a03caa.png)

**Comment by jamie-l-robertson** [comment]
Having the same issue, are there plans to support PHP 8?

**Comment by idflood** [comment]
PHP 8 and 8.1 support would be great, I saw that @joelambert stated working on this here: https://github.com/Rareloop/lumberjack-core/commits/add-php8-support

When hitting this issue I realised that we will have to manually upgrade all our themes based on lumberjack this year to stay on a [maintained php version](https://www.php.net/supported-versions.php). Finger crossed for a smooth upgrade 🤞

**Comment by joelambert** [comment]
PHP 8.0 support was added in `5.0.1` 🎉
