### ISSUE TITLE
zendframework\zend-diactoros is a secondary dependency

### ISSUE THREAD

**Issue by GaryJones** [Rareloop/lumberjack-core#4]
Several `Zend\Diactoros` classes are referenced directly into this repo, even though 
`zendframework\zend-diactoros` is not listed as a dependency.

![screenshot 2018-07-26 11 31 45](https://user-images.githubusercontent.com/88371/43257356-7dad969c-90c7-11e8-9fee-0a6b4a0526fe.png)

In this case, it happens to come from another Rareloop package, but it would still be better practice to add `zendframework\zend-diactoros` to this repo's `composer.json`, so that a change there doesn't unintentionally break something here.

**Comment by adamtomat** [comment]
That's a good point. There might be a couple more of these kicking around too.

I agree it should be added to this repo's `composer.json` 👍.

Feel free to PR, or we'll get around to it when we get a chance.
