### ISSUE TITLE
PHP 8.1 Support ?

### ISSUE THREAD

**Issue by RSickenberg** [Rareloop/lumberjack-core#43]
Any plans to add PHP 8.1 support? AFAIK the only deprecations I got were due to an older version of `"tightenco/collect"`

**Comment by adamtomat** [comment]
👍 We're actively working on it here: 

https://github.com/Rareloop/lumberjack-core/pull/41

**Comment by RSickenberg** [comment]
Thanks @adamtomat ! Will follow
