### ISSUE TITLE
16 Unused Imports

### ISSUE THREAD

**Issue by GaryJones** [Rareloop/lumberjack-core#5]
These imports could be removed since they are unused in the respective file.

![screenshot 2018-07-26 11 35 31](https://user-images.githubusercontent.com/88371/43257595-1d41697c-90c8-11e8-9491-d54dbec243e9.png)

**Comment by adamtomat** [comment]
We're preparing a `v4.0` release so I'll see if we can clean these up as part of that piece of work. Good spot, thanks!

**Comment by GaryJones** [comment]
There are a whole load of other smaller code cleanups that PHPStorm -> Inspections (includes "Php Inspections (EA Ultimate)") found as well :-)
